// test
export const GET_ITEMS = 'GET_ITEMS'
export const ADD_ITEM = 'ADD_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'

// errors
export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

// auth
export const LOGIN = 'LOGIN'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const USER_INFO = 'USER_INFO'
export const GET_USERS = 'GET_USERS'
export const USER_INFO_LOADING = 'USER_INFO_LOADING'
export const REFRESH_AUTH_TOKEN = 'REFRESH_AUTH_TOKEN'
export const LOGOUT = 'LOGOUT'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const REGISTER = 'REGISTER'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const SOCIAL_LOGIN = 'SOCIAL_LOGIN'
export const VALIDATE_AUTH_TOKEN = 'VALIDATE_AUTH_TOKEN'
export const SEND_AUTH_VERIFICATION_PIN = 'SEND_AUTH_VERIFICATION_PIN'
export const VERIFY_AUTH_PIN = 'VERIFY_AUTH_PIN'
export const AUTH_ERROR = 'AUTH_ERROR'

// bank
export const GET_BANKS = 'GET_BANKS'
export const UPDATE_BANK = 'UPDATE_BANK'
export const GET_MY_BANK = 'GET_MY_BANK'

// cart
export const CART_PROCESS = 'CART_PROCESS'
export const UPDATE_CART_ITEM_QUANTITY = 'UPDATE_CART_ITEM_QUANTITY'
export const CART_ITEMS = 'CART_ITEMS'
export const CART_INITIALIZE_CHECKOUT = 'CART_INITIALIZE_CHECKOUT'
export const CART_PROCESS_CHECKOUT = 'CART_PROCESS_CHECKOUT'
export const CART_CASH_PAY = 'CART_CASH_PAY'

// category
export const PRODUCT_CATEGORY = 'PRODUCT_CATEGORY'

// orders
export const ORDERS_HISTORY = 'ORDERS_HISTORY'
export const ORDERS_INVOICE = 'ORDERS_INVOICE'

// payouts
export const VENDOR_REQUEST_PAYOUT = 'VENDOR_REQUEST_PAYOUT'
export const VENDOR_REQUESTED_PAYOUT = 'VENDOR_REQUESTED_PAYOUT'

// product
export const PRODUCT_SEARCH = 'PRODUCT_SEARCH'
export const PRODUCT_VENDORS = 'PRODUCT_VENDORS'
export const PRODUCT_DETAILS = 'PRODUCT_DETAILS'
export const PRODUCT_VENDOR_DETAILS = 'PRODUCT_VENDOR_DETAILS'
export const PRODUCT_FAVORITE = 'PRODUCT_FAVORITE'
export const PRODUCT_MODIFY = 'PRODUCT_MODIFY'
export const PRODCUT_DELETE = 'PRODCUT_DELETE'
export const PRODUCT_IMAGE_SAVE = 'PRODUCT_IMAGE_SAVE'
export const PRODUCT_DELETE_IMAGE = 'PRODUCT_DELETE_IMAGE'
export const PRODUCT_VIEW_FAVORITE = 'PRODUCT_VIEW_FAVORITE'
export const PRODUCT_MODIFY_REVIEWS = 'PRODUCT_MODIFY_REVIEWS'
export const PRODUCT_LIST_REVIEW = 'PRODUCT_LIST_REVIEW'
export const PRODUCT_DELETE_REVIEW = 'PRODUCT_DELETE_REVIEW'

// report
export const REPORT_TOTAL_REVENUE = 'REPORT_TOTAL_REVENUE'
export const REPORT_TOP_SELLERS = 'REPORT_TOP_SELLERS'
export const REPORT_GRAPH_DATA = 'REPORT_GRAPH_DATA'
export const REPORT_DOWNLOAD_REPORT = 'REPORT_DOWNLOAD_REPORT'

// users
export const USER_TRANSACTIONS = 'USER_TRANSACTIONS'
export const USER_PROFILE_UPDATE = 'USER_PROFILE_UPDATE'
export const USER_IMAGE_SAVE = 'USER_IMAGE_SAVE'
export const USER_DISPLAY_DELIVERY_ADDRESS = 'USER_DISPLAY_DELIVERY_ADDRESS'
export const USER_DELIVERY_ADDRESS = 'USER_DELIVERY_ADDRESS'
export const USER_DELIVERY_ADDRESS_DELETE = 'USER_DELIVERY_ADDRESS_DELETE'
export const USER_COMPLETED_ORDER = 'USER_COMPLETED_ORDER'
export const USER_DELETE_ACCOUNT = 'USER_DELETE_ACCOUNT'

// vendor
export const VENDOR_VIEW_PRODUCTS = 'VENDOR_VIEW_PRODUCTS'
export const VENDOR_VIEW_PROFILE = 'VENDOR_VIEW_PROFILE'
export const VENDOR_CONRIM_CASH_PAY = 'VENDOR_CONRIM_CASH_PAY'
export const VENDOR_VIEW_COMPANY_ADDRESS = 'VENDOR_VIEW_COMPANY_ADDRESS'
export const VENDOR_COMPANY_ADDRESS = 'VENDOR_COMPANY_ADDRESS'
export const VENDOR_DELETE_COMPANY_ADDRESS = 'VENDOR_DELETE_COMPANY_ADDRESS'
export const VENDOR_SHOW_REQUEST = 'VENDOR_SHOW_REQUEST'
export const VENDOR_REQUEST_DETAIL = 'VENDOR_REQUEST_DETAIL'
export const VENDOR_ACCEPT_OR_REJECT_REQUEST = 'VENDOR_ACCEPT_OR_REJECT_REQUEST'
export const VENDOR_PROCESS_REQUEST_STATUS = 'VENDOR_PROCESS_REQUEST_STATUS'
export const VENDOR_OPERATION_DAY = 'VENDOR_OPERATION_DAY'
export const VENDOR_VIEW_OPERATION_DAYS = 'VENDOR_VIEW_OPERATION_DAYS'